### ISSUE TITLE
InvalidRequest: The request is malformed or incorrect.

### ISSUE THREAD

**Issue by berryst** [microsoftgraph/msgraph-sample-github-connector-dotnet#47]
Hi,
I was trying to push the repos as part of the step number 5..but I'm getting the following message "InvalidRequest: The request is malformed or incorrect." Below is snippet of some the output. 

_What type of data?
1. Repositories
2. Issues
1
Found 7 repos to push.
Adding/updating repository 101-simple-windows-vm...Error adding/updating repository: 400
InvalidRequest: The request is malformed or incorrect.
Adding/updating repository M365DSC...Error adding/updating repository: 400
InvalidRequest: The request is malformed or incorrect._

Can you please advise? Thank you!

**Comment by berryst** [comment]
I choose a different connection..now it works okay... the one that works for me was **Create a connection in interactive mode** the other one didn't work and resulted the error above

**Comment by jasonjoh** [comment]
I should have been specific about the simplified admin experience - it creates an Issues connector, not a Repository connector. If you tried pushing repos to that connector I would expect that error.
