### ISSUE TITLE
Connect to SharePoint

### ISSUE THREAD

**Issue by beroe-stevemoser** [microsoftgraph/msgraph-sample-github-connector-dotnet#70]
Any tips on extending this sample to build a connector based on our SharePoint or OneDrive folder and publish that connector so that our clients could see our files in their M365 search. Seems like this should be built in or require minimal code given it is connecting a MS product to an MS product. Thoughts, tips?

**Comment by jasonjoh** [comment]
A connector wouldn't be needed for this, unless you're trying to expose files from your M365 tenant to other tenants? If that's the case, then the same basic principles from this sample would apply.
